version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
  water-system-planner:
    image: water-system-planner
    container_name: MAPE_PLANNER
    build:
      context: ./water-system-planner/
      dockerfile: Dockerfile
    volumes:
      - /data/water-system-planner
    ports:
      - "8081:8081"
    networks:
      - iot
  water-system-analyzer:
    image: water-system-analyzer
    container_name: MAPE_ANALYZER
    build:
      context: ./water-system-analyzer/
      dockerfile: Dockerfile
    volumes:
      - /data/water-system-analyzer
    depends_on:
      - influxdb
    networks:
      - iot
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_container
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
  telegraf:
    image: telegraf
    container_name: MAPE_MONITOR
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    depends_on:
      - influxdb
    
  zone:
    image: zone-simulator
    container_name: zone_simulator
    build:
      context: ./zone-simulator/
      dockerfile: Dockerfile
    volumes:
      - /data/zone-simulator
    networks:
      - iot
    depends_on:
      - mosquitto
    restart: always

  
networks:
  iot:
